services:
  api:
    build: .
    container_name: rangos-api
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - .:/app
      - node_modules:/app/node_modules

  mongo:
    image: mongo:5
    container_name: rangos-mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    command: mongod --quiet --logpath /dev/null
    healthcheck:
      test: ['CMD', 'mongo', '--eval', 'db.runCommand("ping").ok']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
  node_modules:
